
// This file is auto-generated by `genkit dev`
// and should not be edited manually.
import type * as merced from '@genkit-ai/googleai';
import type * as brock from 'genkit';
import type *s as yvette from 'zod';
